#!/bin/bash
#
# Downloads the Microsoft-signed UEFI:NTFS loader and NTFS driver binaries from the upstream
# GitHub releases into Sources/SnakeStickCore/Resources/UEFI-NTFS and rewrites VERSIONS.md with
# their sizes and SHA-256 hashes. The signed binaries are stored under their unsigned names
# (bootx64_signed.efi -> bootx64.efi), which is the name the firmware and the loader look for.
#
# usage: Scripts/update-uefi-ntfs.sh <uefi-ntfs tag> <ntfs-3g driver tag>
#        Scripts/update-uefi-ntfs.sh v2.8 1.9
#
# Needs an authenticated `gh`. The binaries are signed by Microsoft and cannot be rebuilt; the
# upstream sources for each tag are linked from VERSIONS.md.

set -euo pipefail

if [ $# -ne 2 ]; then
    echo "usage: $0 <uefi-ntfs tag> <ntfs-3g driver tag>" >&2
    exit 64
fi
LOADER_TAG=$1
DRIVER_TAG=$2
LOADER_REPO=pbatard/uefi-ntfs
DRIVER_REPO=pbatard/ntfs-3g

DEST="$(cd "$(dirname "$0")/.." && pwd)/Sources/SnakeStickCore/Resources/UEFI-NTFS"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

gh release download "$LOADER_TAG" --repo "$LOADER_REPO" --dir "$TMP" \
    --pattern bootx64_signed.efi --pattern bootaa64_signed.efi
gh release download "$DRIVER_TAG" --repo "$DRIVER_REPO" --dir "$TMP" \
    --pattern ntfs_x64_signed.efi --pattern ntfs_aa64_signed.efi
gh api -H "Accept: application/vnd.github.raw" \
    "repos/$LOADER_REPO/contents/LICENSE.txt?ref=$LOADER_TAG" > "$TMP/LICENSE.uefi-ntfs"
LOADER_COMMIT=$(gh api "repos/$LOADER_REPO/commits/$LOADER_TAG" --jq .sha)
DRIVER_COMMIT=$(gh api "repos/$DRIVER_REPO/commits/$DRIVER_TAG" --jq .sha)

mkdir -p "$DEST"
rows=""
for entry in \
    "bootx64.efi bootx64_signed.efi $LOADER_REPO $LOADER_TAG" \
    "bootaa64.efi bootaa64_signed.efi $LOADER_REPO $LOADER_TAG" \
    "ntfs_x64.efi ntfs_x64_signed.efi $DRIVER_REPO $DRIVER_TAG" \
    "ntfs_aa64.efi ntfs_aa64_signed.efi $DRIVER_REPO $DRIVER_TAG"; do
    read -r name asset repo tag <<< "$entry"
    cp "$TMP/$asset" "$DEST/$name"
    size=$(stat -f %z "$DEST/$name")
    sha=$(shasum -a 256 "$DEST/$name" | awk '{print $1}')
    rows+="| \`$name\` | \`$asset\` | $size | \`$sha\` | https://github.com/$repo/releases/download/$tag/$asset |"$'\n'
done
cp "$TMP/LICENSE.uefi-ntfs" "$DEST/LICENSE.uefi-ntfs"

cat > "$DEST/VERSIONS.md" <<EOF
# UEFI:NTFS binaries

Generated by \`Scripts/update-uefi-ntfs.sh $LOADER_TAG $DRIVER_TAG\`. Do not edit by hand; the
test suite checks every file below against its SHA-256.

These files are copied to \`/efi/boot/\` on the FAT partition that SnakeStick puts at the end of
the stick. They are the Microsoft-signed (Secure Boot) builds from the upstream releases, stored
under their unsigned names. They cannot be rebuilt without losing the signature.

| Component | Version | Source (tag, commit) | License |
|---|---|---|---|
| UEFI:NTFS loader | $LOADER_TAG | https://github.com/$LOADER_REPO/tree/$LOADER_TAG ($LOADER_COMMIT) | GNU GPL version 2 (\`LICENSE.uefi-ntfs\`) |
| ntfs-3g UEFI driver | $DRIVER_TAG | https://github.com/$DRIVER_REPO/tree/$DRIVER_TAG ($DRIVER_COMMIT) | GNU GPL version 2 (\`LICENSE.uefi-ntfs\`) |

| File | Release asset | Size | SHA-256 | Downloaded from |
|---|---|---|---|---|
$rows
\`LICENSE.uefi-ntfs\` is \`LICENSE.txt\` from $LOADER_REPO at $LOADER_TAG. The driver repository
carries the same license (GPL version 2) in its \`COPYING\`.
EOF

echo "updated $DEST"
